import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LOGIN</Link>
        </li>
        <li>
          <Link to="/dashboard">DASHBOARD</Link>
        </li>
        <li>
          <Link to="/studentsallstudents">STUDENTSALLSTUDENTS</Link>
        </li>
        <li>
          <Link to="/studentdetails">STUDENTDETAILS</Link>
        </li>
        <li>
          <Link to="/studentsaddstudentone">STUDENTSADDSTUDENTOne</Link>
        </li>
        <li>
          <Link to="/studentsstudentpromotion">STUDENTSSTUDENTPROMOTION</Link>
        </li>
        <li>
          <Link to="/teachersallteacher">TEACHERSALLTEACHER</Link>
        </li>
        <li>
          <Link to="/teachersaddteacher">TEACHERSADDTEACHER</Link>
        </li>
        <li>
          <Link to="/teachersteacherdetails">TEACHERSTEACHERDETAILS</Link>
        </li>
        <li>
          <Link to="/accountfeesgroup">ACCOUNTFEESGROUP</Link>
        </li>
        <li>
          <Link to="/accountstudentfees">ACCOUNTSTUDENTFEES</Link>
        </li>
        <li>
          <Link to="/accountexpenses">ACCOUNTEXPENSES</Link>
        </li>
        <li>
          <Link to="/accountaddexpenses">ACCOUNTADDEXPENSES</Link>
        </li>
        <li>
          <Link to="/subjects">SUBJECTS</Link>
        </li>
        <li>
          <Link to="/settings">SETTINGS</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
